/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';

import '@ionic/core';
import 'ionicons';
import {
  User,
} from './models';


export namespace Components {

  interface AppChest {
    'chestId': string;
    'currentUser': User;
  }
  interface AppChestAttributes extends StencilHTMLAttributes {
    'chestId'?: string;
    'currentUser'?: User;
  }

  interface AppEmail {
    'currentUser': User;
  }
  interface AppEmailAttributes extends StencilHTMLAttributes {
    'currentUser'?: User;
  }

  interface AppHome {}
  interface AppHomeAttributes extends StencilHTMLAttributes {}

  interface AppProfile {
    'name': string;
  }
  interface AppProfileAttributes extends StencilHTMLAttributes {
    'name'?: string;
  }

  interface AppRoot {}
  interface AppRootAttributes extends StencilHTMLAttributes {}

  interface AppStart {
    'currentUser': User;
  }
  interface AppStartAttributes extends StencilHTMLAttributes {
    'currentUser'?: User;
  }
}

declare global {
  interface StencilElementInterfaces {
    'AppChest': Components.AppChest;
    'AppEmail': Components.AppEmail;
    'AppHome': Components.AppHome;
    'AppProfile': Components.AppProfile;
    'AppRoot': Components.AppRoot;
    'AppStart': Components.AppStart;
  }

  interface StencilIntrinsicElements {
    'app-chest': Components.AppChestAttributes;
    'app-email': Components.AppEmailAttributes;
    'app-home': Components.AppHomeAttributes;
    'app-profile': Components.AppProfileAttributes;
    'app-root': Components.AppRootAttributes;
    'app-start': Components.AppStartAttributes;
  }


  interface HTMLAppChestElement extends Components.AppChest, HTMLStencilElement {}
  var HTMLAppChestElement: {
    prototype: HTMLAppChestElement;
    new (): HTMLAppChestElement;
  };

  interface HTMLAppEmailElement extends Components.AppEmail, HTMLStencilElement {}
  var HTMLAppEmailElement: {
    prototype: HTMLAppEmailElement;
    new (): HTMLAppEmailElement;
  };

  interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {}
  var HTMLAppHomeElement: {
    prototype: HTMLAppHomeElement;
    new (): HTMLAppHomeElement;
  };

  interface HTMLAppProfileElement extends Components.AppProfile, HTMLStencilElement {}
  var HTMLAppProfileElement: {
    prototype: HTMLAppProfileElement;
    new (): HTMLAppProfileElement;
  };

  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLAppStartElement extends Components.AppStart, HTMLStencilElement {}
  var HTMLAppStartElement: {
    prototype: HTMLAppStartElement;
    new (): HTMLAppStartElement;
  };

  interface HTMLElementTagNameMap {
    'app-chest': HTMLAppChestElement
    'app-email': HTMLAppEmailElement
    'app-home': HTMLAppHomeElement
    'app-profile': HTMLAppProfileElement
    'app-root': HTMLAppRootElement
    'app-start': HTMLAppStartElement
  }

  interface ElementTagNameMap {
    'app-chest': HTMLAppChestElement;
    'app-email': HTMLAppEmailElement;
    'app-home': HTMLAppHomeElement;
    'app-profile': HTMLAppProfileElement;
    'app-root': HTMLAppRootElement;
    'app-start': HTMLAppStartElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
